### ISSUE TITLE
Doesn't work with Arabic characters

### ISSUE THREAD

**Issue by SwanKnight** [LuminosoInsight/python-ftfy#107]
All messages containing Arabic characters were unreadable.

**Comment by rspeer** [comment]
Can you be more specific? What was the actual text you saw?

**Comment by rspeer** [comment]
Please feel free to re-submit as a valid bug report, with your input, your expected result, and your actual result.

**Comment by SwanKnight** [comment]
Too late, I already lost most of messages. In any case, all message that were in Arabic were unreadable. The result was a bunch of gibberish symbols and characters for all of them.

**Comment by rspeer** [comment]
ftfy works fine in Arabic. Honestly, you seem to be a bit careless with your own data. Whatever problem you saw, I don't think it was a problem in ftfy.

**Comment by rspeer** [comment]
I can't tell *what* you're asking for. Please do not use GitHub Issues like this again.

**Comment by SwanKnight** [comment]
I do _not_ care. Oh piss off!
