### ISSUE TITLE
fix_text not working as expected

### ISSUE THREAD

**Issue by fabiocaccamo** [LuminosoInsight/python-ftfy#120]
Hi, 
thanks for this great library.

The `fix_text` function doesn't fix this:
`b'\x00s\x00t\x00a\x00n\x00d\x00a\x00r\x00d\x00 \x000\x007\x00_\x005\x001`

It should be fixed to:
`standard 07_51.ttf`

**Comment by rspeer** [comment]
python-ftfy doesn't try to interpret UTF-16, because almost any sequence of bytes is valid UTF-16.
