### ISSUE TITLE
Version 5.5.1 not on PyPi?

### ISSUE THREAD

**Issue by wolfgang42** [LuminosoInsight/python-ftfy#121]
I see in the changelog that version 5.5.1 was released on September 14, and #115 was merged on the 24th, but this version never seems to have been published: the [PyPi release history](https://pypi.org/project/ftfy/#history) still lists 5.5.0 as the latest version.

**Comment by rspeer** [comment]
Thanks for reminding me. I've uploaded this version now, as a source archive and a wheel.
