### ISSUE TITLE
Seek guidance in decoding *almost* all escapes

### ISSUE THREAD

**Issue by teledyn** [LuminosoInsight/python-ftfy#128]
ftfy very nearly rescued my data that was munged from unicode into `\u` byte codes!

and seeking guidance on how to get passed the last 5% ...

My source data looks like `Demgem\u00C3\u00A4\u00C3\u009F fiel die Wahl auf ein faltbares Aluminiumzelt 3\u00C3\u00976 Meter.` and the following (possibly naive) sequence decodes it beautifully
```
print(fix_text(decode_escapes("Blitzschneller 1-Hand Aufbau \u00C3\u00BCberzeugt\r\n\r\nSchnelle Pr\u00C3\u00A4senz mit 1 Person und 1 Pavillon.")))
Blitzschneller 1-Hand Aufbau überzeugt

Schnelle Präsenz mit 1 Person und 1 Pavillon.
```
and therein my problem: I need to preserve the \r\n (or any \n) that appears inline within the strings, but convert the \u (or \ddd) items

In a related problem, I also have `\'` and `\"` escapes that need to be protected

Is there a recommended strategy for avoiding this false-positives?

**Comment by rspeer** [comment]
I don't quite understand why you would need to decode some, but not all, of the escapes, but my guess is that you need to work with this string in a JSON or JSON-like context, but you also want it to be readable.

Is it already in a JSON value? You could use Python's `val = json.loads(escaped_string)` and then `json.dumps(val, ensure_ascii=False)`, producing equivalent JSON but with more readable characters.

I don't think this requires ftfy unless it's also tangled up with mojibake or something.
