### ISSUE TITLE
Help needed with garbled text

### ISSUE THREAD

**Issue by cusco** [LuminosoInsight/python-ftfy#133]
Hello,

First off: Thank you for this! I was doing some manual crafting and this saves me time. Thank you

However I'm facing a piece of text that I'm not being able to put it right..
in this case it is outputing the same as it was before:

print(cell)
print(fix_encoding(cell))

Josž? Luž?s
Josž? Luž?s

The desired output would be "José Luís"

Is there something I could do about this?

**Comment by rspeer** [comment]
Unfortunately, if characters have been replaced by question marks (such as by Excel saving text in a non-Unicode-compatible format), there is not enough information to be able to restore the original text.
