### ISSUE TITLE
Mojibake problem: A¯

### ISSUE THREAD

**Issue by MicroJackson** [LuminosoInsight/python-ftfy#138]
Hi again,
Back again with some mojibake problems.
Using ftfy 5.7 and python 3 and ftfy.fix_text(x, uncurl_quotes=False).
```
U+0041  A       [Lu] LATIN CAPITAL LETTER A
U+00AF  ¯       [Sk] MACRON
SHOULD BE:
U+00EF  ï       [Ll] LATIN SMALL LETTER I WITH DIAERESIS
```

Examples:
`LegaA¯a 2 Duel Saga`
`animatie geA¯nspireerde tekeningen`

Is it possible to fix this?

PS:
I had the bright idea to do a full analysis of all my documents for mojibake. After manually shifting through all the data I can say that ftfy fixes most of mojibake problems I have in the documents, but I still have ~45 unique mojibake problems that I think might be solvable. Should I report them all in this style or is another type of reporting style preferable for this many?

**Comment by rspeer** [comment]
I'd be happy to review examples of mojibake found in the wild!

However, to try to filter the reports a bit, ftfy is not going to be able to fix cases like this, where information has been lost that makes it impossible to be certain which character was the original one. And in general, it should be very reluctant to change common ASCII characters like "A".

In this case, the usual windows-1252 mojibake for `Legaïa` would have been `LegaÃ¯a`, but the tilde on the A was removed, which removes the ability to identify the specific intended character.
