### ISSUE TITLE
Mojibake problem: ÃƒÆ'Ã

### ISSUE THREAD

**Issue by MicroJackson** [LuminosoInsight/python-ftfy#139]
Hi,
```
U+00C3  Ã       [Lu] LATIN CAPITAL LETTER A WITH TILDE
U+0192  ƒ       [Ll] LATIN SMALL LETTER F WITH HOOK
U+00C6  Æ       [Lu] LATIN CAPITAL LETTER AE
U+0027  '       [Po] APOSTROPHE
U+00C3  Ã       [Lu] LATIN CAPITAL LETTER A WITH TILDE
SHOULD BE:
U+00EB  ë       [Ll] LATIN SMALL LETTER E WITH DIAERESIS
```

Example:
> haal je AziÃƒÆ'Ã heel dichtbij

Is it possible to fix this?

**Comment by rspeer** [comment]
If `ë`. were encoded in UTF-8 and decoded in windows-1252 three times, it would become `ÃƒÆ’Ã‚Â«`. Some characters were deleted from the string somehow -- perhaps a `«` was removed between the second and third time it was wrongly encoded.

(What is _happening_ to this text?)
