### ISSUE TITLE
Mojibake problem: Ä"

### ISSUE THREAD

**Issue by MicroJackson** [LuminosoInsight/python-ftfy#142]
Hi,
```
U+00C4  Ä       [Lu] LATIN CAPITAL LETTER A WITH DIAERESIS
U+0022  "       [Po] QUOTATION MARK
SHOULD BE:
U+0113  ē       [Ll] LATIN SMALL LETTER E WITH MACRON
```

Example:
> is onze dÄ"zl™ 

Is it possible to fix this?

**Comment by rspeer** [comment]
We can't really fix the ones where the mojibake involved curly quotation marks, which were then straightened into the ASCII quotation mark, because we don't know which curly quotation mark it was originally.
