### ISSUE TITLE
Mojibake problem: â¢

### ISSUE THREAD

**Issue by MicroJackson** [LuminosoInsight/python-ftfy#144]
Hi,
```
U+00E2  â       [Ll] LATIN SMALL LETTER A WITH CIRCUMFLEX
U+00A2  ¢       [Sc] CENT SIGN
SHOULD BE:
U+2022  •       [Po] BULLET
```

Example:
> Finishing â¢ Polished chrome, satin chrome

Is it possible to fix this?

**Comment by rspeer** [comment]
The usual mojibake for the bullet would be `"â€¢"` or `"â\x80¢"`. It looks like the unassigned control character `\x80` was removed, thus losing information about which character it should have been.
