### ISSUE TITLE
Mojibake problem: +»

### ISSUE THREAD

**Issue by MicroJackson** [LuminosoInsight/python-ftfy#145]
Hi,
```
U+002B  +       [Sm] PLUS SIGN
U+00BB  »       [Pf] RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
SHOULD BE:
U+00EF  ï       [Ll] LATIN SMALL LETTER I WITH DIAERESIS
```

Example:
> uitvoering handgreep ge+»ntegreerd

Is it possible to fix this?

**Comment by rspeer** [comment]
I have no idea what caused this one, but the characters in the corrupted text are too plausible to fix anyway.
