### ISSUE TITLE
Mojibake problem: Ã…

### ISSUE THREAD

**Issue by MicroJackson** [LuminosoInsight/python-ftfy#147]
Hi,
```
U+00C3  Ã       [Lu] LATIN CAPITAL LETTER A WITH TILDE
U+2026  …       [Po] HORIZONTAL ELLIPSIS
SHOULD BE:
U+00C5  Å       [Lu] LATIN CAPITAL LETTER A WITH RING ABOVE
```

Example:
> of IKEA TRÃ…DFRI

Is it possible to fix this?

**Comment by rspeer** [comment]
The evidence is there, but it's not enough, because this looks almost like a reasonable string.

There were several examples of false positives that involved all-caps and ellipses (where it really was an all-caps string that got shortened, and the fix was wrong).
