### ISSUE TITLE
Issue in fixing Ã

### ISSUE THREAD

**Issue by swaroopgrs** [LuminosoInsight/python-ftfy#155]
Example: `'S.Ã\xa0 r.l.'`
Desired result:  `'S.à r.l.'`
ftfy output: `'S.Ã\xa0 r.l.'`

```
U+0053  S       [Lu] LATIN CAPITAL LETTER S
U+002E  .       [Po] FULL STOP
U+00C3  Ã       [Lu] LATIN CAPITAL LETTER A WITH TILDE
U+00A0  \xa0    [Zs] NO-BREAK SPACE
U+0020          [Zs] SPACE
U+0072  r       [Ll] LATIN SMALL LETTER R
U+002E  .       [Po] FULL STOP
U+006C  l       [Ll] LATIN SMALL LETTER L
U+002E  .       [Po] FULL STOP
```
`print(ascii('S.Ã\xa0 r.l.'))` -> `'S.\xc3\xa0 r.l.'`
`b'S.\xc3\xa0 r.l.'.decode('utf-8')` -> `'S.à r.l.'`

**Comment by rspeer** [comment]
There isn't enough evidence in that string to fix. Because it's very important for ftfy to avoid false positives, it's intended that we don't change a string solely because it has a capital letter followed by a non-breaking space -- that is a normal thing that can occur in text.
