### ISSUE TITLE
Problem fixing "×‘×”×•×“×¢×”" (Hebrew)

### ISSUE THREAD

**Issue by SuperIRabbit** [LuminosoInsight/python-ftfy#158]
To reproduce:
word = "×‘×”×•×“×¢×”"
fix_encoding(word)

Output: "×‘×”×•×“×¢×”"

Expected output (Hebrew): "בהודעה"

**Comment by rspeer** [comment]
Thanks. There is a part of the heuristic that was _supposed_ to handle the case of Hebrew that's full of multiplication signs, but due to a regex mistake, it's not actually working.

If I just fix the regex to what I intended, it breaks a different test case, so I'm looking at how to revise it.

**Comment by rspeer** [comment]
Oh, this was fixed as part of 5.8.
