### ISSUE TITLE
Website isn't working

### ISSUE THREAD

**Issue by endolith** [LuminosoInsight/python-ftfy#163]
If you click all the example links at the bottom, this one does not work:

https://ftfy.now.sh/?s=%23%E2%95%A8%E2%94%90%E2%95%A4%C3%87%E2%95%A8%E2%96%91%E2%95%A8%E2%96%93%E2%95%A8%E2%95%95%E2%95%A8%E2%95%97%E2%95%A4%C3%AE%E2%95%A8%E2%95%9C%E2%95%A8%E2%95%9B%E2%95%A8%E2%95%A1%E2%95%A8%E2%94%90%E2%95%A8%E2%95%95%E2%95%A4%C3%A9%E2%95%A8%E2%96%91%E2%95%A8%E2%95%9C%E2%95%A8%E2%95%95%E2%95%A8%E2%95%A1

**Comment by rspeer** [comment]
I didn't make the website. The github repo you're looking for is: https://github.com/simonw/ftfy-web
