### ISSUE TITLE
Behaviour change wrt color escape sequence in 6.0

### ISSUE THREAD

**Issue by pmezard** [LuminosoInsight/python-ftfy#173]
Hello,

No sure if this is a bug or feature.

In 5.9:
```
>>> ftfy.fix_text("\001\033[36;44mfoo")
'foo'
```

In 6.0:
```
>>> ftfy.fix_text("\001\033[36;44mfoo")
'[36;44mfoo'
```

Thanks!

**Comment by rspeer** [comment]
You're right -- this step turned out to be missing. I'm pushing a fix to restore it in 6.0.1.
