### ISSUE TITLE
Commitment to future maintenance 

### ISSUE THREAD

**Issue by hickford** [LuminosoInsight/python-ftfy#175]
Hi. I read that the [principal maintainer](https://github.com/LuminosoInsight/python-ftfy/graphs/contributors) @rspeer has left the company. This can be a difficult transition for an open source project. Can anyone offer a reassuring statement of future commitment to maintaining this library?

https://blog.conceptnet.io/posts/2021/future/

> Robyn Speer April 16, 2021. Today is my last day at Luminoso, and I won’t be able to update this copy of the site anymore.

**Comment by rspeer** [comment]
Hi, hickford. While I've been taking a bit of a break, I'm going to continue to maintain this library. I'll probably be forking a copy under my own username soon.

**Comment by hickford** [comment]
Brilliant, thanks Robyn for confirming
