### ISSUE TITLE
ftfy bin folder conflicts if packed with other libraries.

### ISSUE THREAD

**Issue by vijayendra-tripathi** [LuminosoInsight/python-ftfy#177]
Thanks for all your hardwork on ftfy library.

I am facing an issue while installing it using pip. I need to pack this library with several other libraries but ftfy creates a bin folder while installing it into a targeted folder. Since bin folder already exists there (created by another library), the command asks me to use forece to replace it. I checked ftfy bin folder has a file called "ftfy" and I am not sure if it really needed by the library. I just want to confirm if the code needs this binary file to work?

**Comment by rspeer** [comment]
The binary is a command line script that runs ftfy on a file. It's created by the usual setuptools process of making an "entry point". It's not necessary for using ftfy as a library.
