### ISSUE TITLE
pip install -U ftfy on Windows XP 32-bit fails

### ISSUE THREAD

**Issue by dineshbvadhia** [LuminosoInsight/python-ftfy#33]
Installing ftfy on Windows 32-bit under the Python Anaconda (2.1) distribution:

C:\>pip install -U ftfy
Collecting ftfy
  Using cached ftfy-3.4.0.tar.gz
    C:\Anaconda\lib\distutils\dist.py:267: UserWarning: Unknown distribution opt
ion: 'entry_points'
      warnings.warn(msg)
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    error: invalid command 'egg_info'
    Complete output from command python setup.py egg_info:
    C:\Anaconda\lib\distutils\dist.py:267: UserWarning: Unknown distribution opt
ion: 'entry_points'

      warnings.warn(msg)

    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]

       or: -c --help [cmd1 cmd2 ...]

       or: -c --help-commands

       or: -c cmd --help

    error: invalid command 'egg_info'
    ----------------------------------------
←[31m    Command "python setup.py egg_info" failed with error code 1 in c:\docum
e~1\dinesh\locals~1\temp\pip-build-tng72e\ftfy←[0m

**Comment by rspeer** [comment]
I don't know much about Anaconda, but it sounds like you've got an obsolete version of setuptools, as described by this StackOverflow thread: http://stackoverflow.com/questions/11425106/python-pip-install-fails-invalid-command-egg-info

It's possible that you can fix the problem with `pip install --upgrade setuptools`.

But I'm surprised that the current version of Anaconda would ship with such an obsolete setuptools. Are you sure you're running the `pip` from Anaconda, as opposed to another version that happens to be on your PATH?

**Comment by dineshbvadhia** [comment]
The version of setuptools is 14.0.  

"pip install -U ftfy" generates same error as before.

Typically, Anaconda updates all core packages every few months plus you can manually update packages at any time.

pip installs into the Anaconda environment plus I don't have any other Python environments.

Will install on Windows 8.1 tomorrow and will you know.

**Comment by rspeer** [comment]
I just tried the setup script in a fresh Python environment, with setuptools 14.0 (the current version), and it worked fine, including the `egg_info` command.

So I think this is a bug in Anaconda. Why is pip passing information designed for setuptools straight to `distutils.dist`, which doesn't understand it?

**Comment by dineshbvadhia** [comment]
Thanks for the swift reply. Will check with the Anaconda group and get back.

**Comment by dineshbvadhia** [comment]
Btw, downloaded the ftfy zip and "python setup.py install" worked into the Anaconda environment.
