### ISSUE TITLE
Explain the `restore_byte_a0` function a bit better

### ISSUE THREAD

**Issue by heinrich5991** [LuminosoInsight/python-ftfy#38]
Why is it needed? How does a space get encoded to `\xa0`? (Would fit into the documentation, I guess.)

**Comment by rspeer** [comment]
It's the other way around -- something expecting Windows-1252 or a similar encoding said "hmm, `\xa0`, that's kind of like a space!" and just replaced it with a space. We need to put back the `\xa0` to get a sequence that would decode as UTF-8. The fact that ftfy 4.0 tries this is what made it successfully decode the W3C WTF-8 tweet (https://twitter.com/koalie/status/506821684687413248), for example.

Sure, I'll document this better.

**Comment by heinrich5991** [comment]
That's interesting. Thanks for the explanation!
