### ISSUE TITLE
Fix Failure

### ISSUE THREAD

**Issue by OverlordQ** [LuminosoInsight/python-ftfy#39]
Input: Àëüÿíñ ðóññêèõ è ÈÀÏË âìåñòå áóäóò ó÷àñòâîâàòü â âûáîðàõ â Åâðîïàðëàìåíò
Expected Output: Глава НАТО призывает Россию отмежеваться от заявлений Жириновского о Балтии

Result of requests incorrectly guessing the encoding of text as ISO-8859-1 instead of Windows-1251.

**Comment by rspeer** [comment]
Thanks, but this is a duplicate of #18.

I've been trying to think of the appropriate way to implement that feature for a while.
