### ISSUE TITLE
Feature: Replace unicode specials block characters?

### ISSUE THREAD

**Issue by theconor** [LuminosoInsight/python-ftfy#47]
Great tool, very useful!  Its working brilliantly for most text I throw at it; I've just got the occasional documents that appear to have some rogue sequences of unicode "special blocks" characters in them.

e.g.

```
>ftfy.explain_unicode(txt):
U+000A  \n      [Cc] <unknown>
U+FFFC  ￼       [So] OBJECT REPLACEMENT CHARACTER
U+FFFC  ￼       [So] OBJECT REPLACEMENT CHARACTER
U+FFFC  ￼       [So] OBJECT REPLACEMENT CHARACTER
U+0042  B       [Lu] LATIN CAPITAL LETTER B
U+0072  r       [Ll] LATIN SMALL LETTER R
U+0065  e       [Ll] LATIN SMALL LETTER E
U+0072  r       [Ll] LATIN SMALL LETTER R
U+0065  e       [Ll] LATIN SMALL LETTER E
U+0074  t       [Ll] LATIN SMALL LETTER T
U+006F  o       [Ll] LATIN SMALL LETTER O
U+006E  n       [Ll] LATIN SMALL LETTER N
U+0020          [Zs] SPACE
U+0047  G       [Lu] LATIN CAPITAL LETTER G
U+0072  r       [Ll] LATIN SMALL LETTER R
U+0065  e       [Ll] LATIN SMALL LETTER E
U+0065  e       [Ll] LATIN SMALL LETTER E
U+006E  n       [Ll] LATIN SMALL LETTER N
```

For my case, output would look best if the Object Replacement Characters could be converted to spaces.  Same for other similar characters in the same unicode block.

Note: I'm not sure of the origin of this text, it looks like it has been copied&pasted from elsewhere, but suffice to say the  ￼ characters are certainly not intended for the output.  It would be nice if ftfy had an option to remove them directly (apologies if I've missed it).

**Comment by rspeer** [comment]
This is interesting. I've wondered for a while what U+FFFC is supposed to be used for. I'm still not sure,

However, if this is something ftfy should automatically fix, I'd want to understand what process produced it. After all, if it's just an isolated incident that you've got U+FFFC's that you don't want, you could run txt.replace('\ufffc', '') without needing any additional code in ftfy. But if there's some common workflow of text that causes these characters to show up meaninglessly, then it would make sense to automatically remove them.

**Comment by theconor** [comment]
Hi, here is an example source document:
https://www.contractsfinder.service.gov.uk/Notice/ad819caa-91f3-43fb-9c46-5f6ea21e1564
It looks like the content has been pasted into a webform from another document type -- I'm afraid I don't know anything about what applications might have been involved.
The ￼ case is actually pretty uncommon -- happening in just 2 documents so far -- but the reason I raised that is that lxml refused to parse the document before they were removed.  I've already done that with a simple replace as you've suggested. 
The related character U+FFFD � is slightly more common in this source, but thankfully does not cause the same problem with lxml and I have already removed it using the method described above.

Feel free to close this off if it is not a common problem.

NB.  Some information about Object Replacement Character in this document:

http://unicode.org/reports/tr20/tr20-1.html

> 3.1 Object Replacement Character, U+FFFC
> 
> Short description: The object replacement character is used to stand in place of an object (e.g. an image) included in a text.
> 
> Reason for inclusion: The object replacement character was included in Unicode only in order to reserve a codepoint for a very frequent application-internal use. Many text-processing applications store the text and the associated markup (or in some cases styling information) of a document in separate structures. The actual text is kept in a single linear structure; additional information is kept separately with pointers to the appropriate text positions. The overall implementation makes sure that these two structures are kept in sync. If the text contains objects such as images, it is extremely helpful for implementations to have a sentinel in the text itself; any additional information is kept separately.
> 
> Problems when used in markup: Including an object replacement character in markup text does not work because the additional information (what object to include,...) is not available.
> 
> Problems with other uses: The object replacement character is also problematic when used in plain text.
> 
> Replacement markup: The markup to be used in place of the Object Replacement Character depends on the object in question and the markup context it is used in. Typical cases are <html:img src'...' />, <html:object ...>, or <html:applet ...>. These constructs allow to provide all additional information needed to identify and use the object in question.
> 
> What to do if detected: In a proxy context or browser context, ignore. When received in an editing context, remove, maybe with a warning to the user.

**Comment by rspeer** [comment]
Frequencies of these characters in a sample of millions of Tweets:

* U+FFFC: 925 occurrences
* U+206x: 318 occurrences total (where do these come from?)
* U+FEFF: 1 occurrence (but I know I've seen it more frequently elsewhere)
* Others: never used

**Comment by rspeer** [comment]
Scanning through some of the Common Crawl, I'm finding that most of these characters seem to appear only in Unicode tables or in arbitrary binary data that wasn't meant to be decoded as UTF-8. The ruby-annotation characters are never used for any purpose, so I shouldn't need to worry about what it looks like to remove them.

I really can't tell what people are using U+206A through U+206F for. They tend to appear in blocks of emoji on Twitter. It seems to have nothing to do with the Arabic control characters they were meant to be.

And you are not the only person to have U+FFFC sprinkled throughout their text. So I agree with the suggestion to make a general fixer that removes a lot of these characters.

**Comment by theconor** [comment]
That sounds good to me - thanks for looking into this!
On U+206x, there's a book snippet here that explains most of the characters, and specifically it describes them as "invisible formatting characters".  My vote would be to remove them :-)
https://books.google.co.uk/books?id=wn5sXG8bEAcC&pg=PA475&lpg=PA475&dq=unicode+Symmetric+swapping&source=bl&ots=J1bEsZVfWA&sig=J_WyIGbVr8qhZS8COq9KxKy73Fg&hl=en&sa=X&ved=0ahUKEwiK87rzhbzLAhVFOBoKHZ46BCI4ChDoAQg-MAc#v=onepage&q=unicode%20Symmetric%20swapping&f=false

> Unicode Demystified: A Practical Programmer's Guide to the Encoding Standard
> Richard Gillam
> Addison-Wesley Professional, 2003 - Computers - 853 pages
Page 475: "Deprecated Characters"
