### ISSUE TITLE
CLI broken with Python 3: tries to decode STDIN as UTF-8 even when different encoding is specified

### ISSUE THREAD

**Issue by texttheater** [LuminosoInsight/python-ftfy#48]
With ftfy installed as a Python 3 package on my Ubuntu 14.04 machine, this happens:

    $ echo Æèçíü íà ìåñòå | iconv -f utf8 -t latin1 | ftfy -e sloppy-windows-1251
    ftfy error:
    This input couldn't be decoded as 'sloppy-windows-1251'. We got the following error:
    
        'utf-8' codec can't decode byte 0xc6 in position 0: invalid continuation byte
    
    ftfy works best when its input is in a known encoding. You can use `ftfy -g`
    to guess, if you're desperate. Otherwise, give the encoding name with the
    `-e` option, such as `ftfy -e latin-1`.

With ftfy installed as a Python 2 package, it works as expected:

    $ echo Æèçíü íà ìåñòå | iconv -f utf8 -t latin1 | ftfy -e sloppy-windows-1251
    Жизнь на месте

BTW, awesome package!

**Comment by rspeer** [comment]
Aha, yes, I should be using `sys.stdin.buffer` on Python 3 because `sys.stdin` already has an encoding it expects. I'll fix it.

**Comment by rspeer** [comment]
Fixed by https://github.com/LuminosoInsight/python-ftfy/pull/49 .
