### ISSUE TITLE
Custom html entity defs

### ISSUE THREAD

**Issue by chbrown** [LuminosoInsight/python-ftfy#50]
I ran into some text that uses [non-standard](https://www.w3.org/TR/html4/sgml/entities.html) html entities...

``` html
&Ccaron; &Sacute; &Scedil; &cacute; &ccaron; &nacute; &ncaron; &scedil; &slig; &zcaron;
```

...which are apparently supported in some browsers (all of these but `&slig;` resolve to a real character in Chrome 51):

> &Ccaron; &Sacute; &Scedil; &cacute; &ccaron; &nacute; &ncaron; &scedil; &slig; &zcaron;

Currently I'm using the following hack, which _works_, but, well, it's a hack:

``` python
from ftfy import fix_text
from ftfy.fixes import htmlentitydefs
nonstandard_entities = [
    ('ccaron', u'č'), ('Ccaron', u'Č'), ('cacute', u'ć'), ('Sacute', u'Ś'),
    ('Scedil', u'Ş'), ('nacute', u'ń'), ('ncaron', u'ň'), ('scedil', u'ş'),
    ('slig', u'ß'), ('zcaron', u'ž'),
]
for name, unicode_value in nonstandard_entities:
    htmlentitydefs.name2codepoint[name] = ord(unicode_value)
# and then later I use fix_text() as usual
```

I'd prefer to be able to pass in my own `htmlentitydefs` to `fix_text(...)`, or perhaps just the `name2codepoint` mapping, since that's all that `ftfy.fixes.unescape_html(text)` uses.

What do you think? Too much argument bloat?

**Comment by rspeer** [comment]
Sorry for letting this suggestion lapse.

I think it would be argument bloat to make the entities customizable, but on the other hand, my design goal is to make the right thing happen as often as possible, so I could just code in some extra entities. Is this the entire list of sometimes-accepted but non-standard HTML entities, or are there more?

**Comment by chbrown** [comment]
That's not the entire list by any means, just the entity-looking things that showed up in my particular messily-encoded file. :)

I don't know if there's a good standard list somewhere, since those characters are outside the W3 spec, but here's some relevant [Chromium source code](https://cs.chromium.org/search/?q=Sacute&sq=package:chromium&type=cs) and some from [WebKit](https://github.com/WebKit/webkit/search?utf8=%E2%9C%93&q=Sacute) (using "Sacute" as a relatively unambiguous search term). Or maybe it'd be easier to incorporate the [already-Python constants](https://github.com/html5lib/html5lib-python/blob/1.0b10/html5lib/constants.py) from html5lib?

That full html5lib list might be overboard, though? There are quite a few characters in there!

    In [1]: import html5lib; len(html5lib.constants.entities)
    Out[1]: 2231

**Comment by rspeer** [comment]
A desirable outcome for me is a list of entities that I don't have to curate myself, and html5lib looks like a good choice there. If it's important to decode these entities in an HTML5 parser, it's probably also important in ftfy.

(The best thing would be to replace the whole function with `html.unescape` from the standard library, but that's a Python 3.4+ thing, and, y'know, long before I drop support for Python 3.3, I have to drop support for 2.6 and 2.7 and see how mad people get.)

**Comment by chbrown** [comment]
`html5lib` is a pretty sizable project to depend on, but its dependencies, `six` and `webencodings`, seem reasonable. I agree with your judgment here and the solution in 		c960156.
