### ISSUE TITLE
Vietnamese is not weird!

### ISSUE THREAD

**Issue by shueffner** [LuminosoInsight/python-ftfy#55]
Hello,
I've been getting high weirdness scores for texts that seem benign, like:

Mấy thằng vệ sỉ này muốn xơi nó củng khó, thịt không ăn hoài không hết!
Google Translate tells me that this is Vietnamese.
It has weirdness 14.

**Comment by rspeer** [comment]
I noticed this too -- it was a heuristic that we don't need anymore being overly picky -- and it was fixed in commit d51b41c. However, I haven't made a release with that change yet. This is a good reminder that I should release that change.

**Comment by rspeer** [comment]
ftfy 4.2 is up with the fix.
