### ISSUE TITLE
Some emojis are considered "weird"

### ISSUE THREAD

**Issue by shueffner** [LuminosoInsight/python-ftfy#56]
Hello,
I cannot post the example here, but I can post the "explain unicode":
U+FE0F  ️       [Mn] VARIATION SELECTOR-16
U+2764  ❤       [So] HEAVY BLACK HEART
I have a post with a sequence of these, and it receives a high weirdness score (as high as the number of hearts as above).

**Comment by rspeer** [comment]
Yep. Similarly to the other bug, this was fixed in 1e3f2b6 and just needs to be released.
