### ISSUE TITLE
documentation: But gb18030 is a UTF.

### ISSUE THREAD

**Issue by Artoria2e5** [LuminosoInsight/python-ftfy#57]
> We also can’t handle the non-UTF encodings used for Chinese, Japanese, and Korean, such as shift-jis and gb18030. See issue #34 for why this is so hard.

But GB18030 is a UTF! It handles [every code point but surrogates](https://en.wikipedia.org/wiki/GB_18030#Mapping), which is good enough to meet [this definition](http://unicode.org/faq/utf_bom.html):

> A Unicode transformation format (UTF) is an algorithmic mapping from every Unicode code point (except surrogate code points) to a unique byte sequence.

I guess there will be some rewording needed. Perhaps just replace gb18030 with gbk.

PS: members of the GB family may be partially identifiable given the following features:
- Most characters found in common GB strings fall inside the GB2312-1980 (EUC-CN) range. EUC G1 bytes don't overlap with ASCII byte range.
- GB 18030's 4-byte sequences are highly visible to human in some otherwise GBK soup, as GBK does not make use of 0x30-0x39 for its 2-byte encoding.

**Comment by rspeer** [comment]
I don't think it would be common to call GB18030 a "UTF", despite the definition you give. Even if I changed the example, it wouldn't make GB18030 any easier to fix heuristically.

It's true that the G1 bytes (0x81 through 0xFE) don't overlap with ASCII, but they *do* overlap with UTF-8 (which is several orders of magnitude more common) and all the old single-byte codepages. Issue #34 is an illustrative example: the user thought he was decoding damaged GB18030 when it was actually damaged UTF-8, and the output was convincing to someone who didn't read Chinese.

As far as I can tell, the only way to get *negative* evidence for decoding something as GB* is to recognize the result as "that's not Chinese" -- that is, to have a Chinese language model.

In the long term I'd be interested in distinguishing encodings via language models, but in a separate project, not as part of ftfy (that would be scope creep).

**Comment by Artoria2e5** [comment]
> I don't think it would be common to call GB18030 a "UTF", despite the definition you give. Even if I changed the example, it wouldn't make GB18030 any easier to fix heuristically.

Hmm. What about rewording to something like "legacy encodings"?
