### ISSUE TITLE
Weird Asian characters not fixed

### ISSUE THREAD

**Issue by heinrich5991** [LuminosoInsight/python-ftfy#58]
I have a couple of filenames that are encoded and decoded on various operating systems without any respect to Unicode, and what I got is something like this:

```
U+9DED  鷭      [Lo] CJK UNIFIED IDEOGRAPH-9DED
```
that should be
```
U+00F8  ø       [Ll] LATIN SMALL LETTER O WITH STROKE
U+0073  s       [Ll] LATIN SMALL LETTER S
```
---
```
U+6DEA  淪      [Lo] CJK UNIFIED IDEOGRAPH-6DEA
```
↓
```
????????????????????????????? (maybe a base 10 Arabic digit)
U+005F  _       [Pc] LOW LINE
```
---
```
U+7FB9  羹      [Lo] CJK UNIFIED IDEOGRAPH-7FB9
```
↓
```
U+00FC  ü       [Ll] LATIN SMALL LETTER U WITH DIAERESIS
```
---
```
U+E15D  \ue15d  [Co] <unknown>
```
↓
```
U+00FC  ü       [Ll] LATIN SMALL LETTER U WITH DIAERESIS
```

Any ideas would be appreciated.

I'm especially interested in the ??? character. :)

**Comment by rspeer** [comment]
I wouldn't get your hopes up too much -- as I look into supporting more cases of mojibake, I continually notice that CJK mojibake is the *worst*. (I guess there's a reason they invented the word.)

The major Japanese and Chinese encodings seem to have been designed to be as confusable with each other as possible, and on top of that you can sometimes mix up Japanese in Shift-JIS with UTF-8 and get valid Chinese characters out.

I'm still interested to know what your particular case of mojibake is, but I would need to see the entire strings and what they turned into, not just single characters.
