### ISSUE TITLE
Curly quotes get transformed into "normal" quotes

### ISSUE THREAD

**Issue by f11r** [LuminosoInsight/python-ftfy#59]
The following code  
~~~
import ftfy
ftfy.fix_text('„')
~~~
gives  `'"'` as output. Is this correct or should it keep `„` instead? The same goes for `“`.

**Comment by rspeer** [comment]
All the transformations are on by default, and normalizing quotation marks is a kind of cleanup that many people are looking for in a text pipeline. The option you're looking for is:

```python
>>> ftfy.fix_text('„', uncurl_quotes=False)
'„'
```

**Comment by f11r** [comment]
Thx. Should have read the docs more carefully.
