### ISSUE TITLE
Fails to fix if the transformation are preceded by "…"

### ISSUE THREAD

**Issue by prashnts** [LuminosoInsight/python-ftfy#72]
I noticed that nothing is transformed after `…` character:

```python
>>> ftfy.fix_text('said… â\x80\x9cOverall an')
'said… â\x80\x9cOverall an'
>>> ftfy.fix_text('said â\x80\x9cOverall an')
'said "Overall an'
```

**Comment by rspeer** [comment]
This is correct. Any transformation that could possibly happen would break the `…` character, which is already correct Unicode, and ftfy aims to never turn correct text into incorrect text.

If you know that the text up to "said…" is encoded differently from the text after it, pass those two substrings separately to `ftfy.fix_text_segment`.

I recognize that there are many cases where strings from different sources are joined together, and one of them is truncated and ends with an ellipsis. But I don't see a way to automatically use the ellipsis to detect that case -- it tells you where a differently-encoded string ends, but how would you know where it begins?

**Comment by prashnts** [comment]
Yeah, I agree. I realised later on that I was stripping a line break after `…` character. Preserving that returns correct test. That is, the following works:

```python
>>> ftfy.fix_text('said…\nâ\x80\x9cOverall an')
'said…\n"Overall an'
```
 
Thanks for the quick response! Big fan of `ftfy`. :)
