### ISSUE TITLE
ftfy-4.4.2: Nix build from PyPi fails on Linux and OS X due to non-ASCII character '\xc5'

### ISSUE THREAD

**Issue by sdll** [LuminosoInsight/python-ftfy#75]
Please see [GNU/Linux Build](https://travis-ci.org/NixOS/nixpkgs/jobs/232370373)  and [OS X Build](https://travis-ci.org/NixOS/nixpkgs/jobs/232370374) on Nix Travis CI.

The culprit file is tests/test-entities.py.

The source tar ball is fetched from the PyPi repository.

**Comment by rspeer** [comment]
Got it, thanks. I added the `# coding: utf-8` declaration to two files that were missing it. This fix is on the `version4.4` branch and released to PyPI.
