### ISSUE TITLE
Vietnamese text doesn't fix correctly.

### ISSUE THREAD

**Issue by QuangHoang** [LuminosoInsight/python-ftfy#77]
I use the fix_text method to this the text below, but sounds like it doesn't work.

Input: u'N\xe1"\x91i l\xe1\xba\xa1i tu\xe1\xba\xa7n tra, ch\xc3\xadnh quy\xe1"\x81n Trump x\xc3\xb3a tan nghi ng\xe1"\x9d \xe1"\x9f Bi\xe1"\x83n \xc4\x90\xc3\xb4ng '

Ouput: Ná"i láº¡i tuáº§n tra, chÃ­nh quyá"n Trump xÃ³a tan nghi ngá" á" Biá"n ÄÃ´ng

Expected output: Nối lại tuần tra, chính quyền Trump xóa tan nghi ngờ ở Biển Đông

import requests
from readability import Document
from ftfy import fix_text
 
def extract(url):
    response = requests.get(url)
    doc = Document(response.text)
    return doc.title()

t = extract('http://vnexpress.net/tin-tuc/the-gioi/phan-tich/noi-lai-tuan-tra-chinh-quyen-trump-xoa-tan-nghi-ngo-o-bien-dong-3590033.html')
print(t)
u'N\xe1"\x91i l\xe1\xba\xa1i tu\xe1\xba\xa7n tra, ch\xc3\xadnh quy\xe1"\x81n Trump x\xc3\xb3a tan nghi ng\xe1"\x9d \xe1"\x9f Bi\xe1"\x83n \xc4\x90\xc3\xb4ng - VnExpress'

print(fix_text(t))
u'N\xe1"\x91i l\xe1\xba\xa1i tu\xe1\xba\xa7n tra, ch\xc3\xadnh quy\xe1"\x81n Trump x\xc3\xb3a tan nghi ng\xe1"\x9d \xe1"\x9f Bi\xe1"\x83n \xc4\x90\xc3\xb4ng - VnExpress'

**Comment by rspeer** [comment]
The `readability` library seems to have already messed with your text in a way that loses information. (I tried installing it, but it's not the library you get from `pip install readability`, so I don't really know what it is.)

The string you have has been mojibaked, and then the character `\xbb` has been replaced with a quotation mark (`"`). If we undo that last destructive change, ftfy can fix it:

```python
>>> ftfy.fix_text(t.replace('"', '\xbb'))
'Nối lại tuần tra, chính quyền Trump xóa tan nghi ngờ ở Biển Đông '
```

I can work around using Readability by using html5lib instead, and it means I have to deal with ElementTree XML awfulness, but I can get the text, and ftfy can fix it:

```
>>> data = requests.get("http://vnexpress.net/tin-tuc/the-gioi/phan-tich/noi-lai-tuan-tra-chinh-quyen-trump-xoa-tan-nghi-ngo-o-bien-dong-3590
... 033.html").text
>>> html = html5lib.parse(data)
>>> element = html.find('{http://www.w3.org/1999/xhtml}head/{http://www.w3.org/1999/xhtml}title')
>>> element.text
'Ná»\x91i láº¡i tuáº§n tra, chÃ\xadnh quyá»\x81n Trump xÃ³a tan nghi ngá»\x9d á»\x9f Biá»\x83n Ä\x90Ã´ng - VnExpress'
>>> ftfy.fix_text(element.text)
'Nối lại tuần tra, chính quyền Trump xóa tan nghi ngờ ở Biển Đông - VnExpress'
```

**Comment by QuangHoang** [comment]
The library I used was https://github.com/buriy/python-readability

Install: pip install readability-lxml
