### ISSUE TITLE
Add (recursive) processing of files in directories to the command-line tool

### ISSUE THREAD

**Issue by Socialdarwinist** [LuminosoInsight/python-ftfy#79]
It would require fixing of #78 too, and a special value called maybe “selfsamefile” for the “--output” argument or another argument for having the selfsame files as output rather than the standard output.
We could differentiate whether files in subfolders are affected by an additional “--recursive” argument.

Actually, processing of whole folders is the crucial feature one desires from the command-line tool in ftfy, because one is hardly slower just opening and resaving files with medit or an other encoding aware editor for the purpose of fixing files ony by one.

**Comment by rspeer** [comment]
This and #80 both sound out-of-scope. You could use ftfy to create a recursive file-fixing tool, but we shouldn't add a lot of file management to ftfy for one particular use case.

But also, if opening and saving with an editor is sufficient to fix the file, that sounds like a case where ftfy is hardly necessary -- it sounds like it's just in an unknown encoding, not mojibaked.
