### ISSUE TITLE
Add processing of mere filenames

### ISSUE THREAD

**Issue by Socialdarwinist** [LuminosoInsight/python-ftfy#80]
It is desirable to have a tool to fix mojibake filenames, using for example a --filenameonly flag, which can sometimes come in whole collections (made by archivers or otherwise coming from inferior operating systems) and are at least an aesthetical chagrin, therefore this should be implemented in addition to #79. As for the “output” argument, it would again be desirable to have a special value for it called maybe “tofilename” or another argument for renaming the files instead of expressing the conversion result in stdout.

**Comment by rspeer** [comment]
As with #79, this is out of scope. You could create a Python script that fixes filenames using ftfy.
