### ISSUE TITLE
Problems with fix_latin_ligatures and ftfy 4.4.3

### ISSUE THREAD

**Issue by pannal** [LuminosoInsight/python-ftfy#81]
Hey,

A user of mine is receiving the following error with fix_latin_ligatures enabled:
```
File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/ftfy/__init__.py", line 183, in fix_text
    normalization=normalization
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/ftfy/__init__.py", line 277, in fix_text_segment
    text = fixes.fix_latin_ligatures(text)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/ftfy/fixes.py", line 381, in fix_latin_ligatures
    return text.translate(LIGATURES)
TypeError: character mapping must return integer, None or unicode
```

The text is a subtitle in unicode. It seems like LIGATURES should look like this instead:
```
LIGATURES = {
    ord(u'Ĳ'): u'IJ',
    ord(u'ĳ'): u'ij',
    ord(u'ﬀ'): u'ff',
    ord(u'ﬁ'): u'fi',
    ord(u'ﬂ'): u'fl',
    ord(u'ﬃ'): u'ffi',
    ord(u'ﬄ'): u'ffl',
    ord(u'ﬅ'): u'ſt',
    ord(u'ﬆ'): u'st'
}
```

I can PR if you like.

**Comment by pannal** [comment]
Wait, that's not your fault. I changed the fixes.py because I needed to remove unicode_laterals.

**Comment by pannal** [comment]
Are you sure `ord(u'ﬅ'): u'ſt',` is correct, though? Shouldn't it be `ord(u'ﬅ'): u'ft',`?

**Comment by Tahnan** [comment]
`ﬅ` isn't a ligature for `f` and `t`; it's U+FB05, "LATIN SMALL LIGATURE LONG S T".  So `ſt` (a Latin small letter long S and a Latin small letter T) is correct.

**Comment by pannal** [comment]
OK, thank you.

**Comment by Tahnan** [comment]
Quick followup: using normalization `NFKC` confirms that ftfy is doing the right thing here:

```
>>> ftfy.fix_text('the purſuit of happineſs is juﬅ')
'the purſuit of happineſs is juſt'

>>> ftfy.fix_text('the purſuit of happineſs is juﬅ', normalization='NFKC')
'the pursuit of happiness is just'
```

(Which I mention only because my immediate reaction was "should ftfy be normalizing the long S?", only to discover that yes, it does, if you ask it to.)
