### ISSUE TITLE
need help for fixing a text

### ISSUE THREAD

**Issue by jabbalaci** [LuminosoInsight/python-ftfy#82]
I have the following text: "WalldÃ?Â©n". I know that correctly it is "Walldén" ("Walld\u00e9n"). `ftfy.fix_text` returns the same text:

    s = "WalldÃ?Â©n"                                                                                                                                                                              
    print(ftfy.fix_text(s))     # prints "WalldÃ?Â©n"

Do you know how to correct this text? Thanks.

**Comment by ArtemBernatskyy** [comment]
Same here, original source is `Стрела` , mutagen library returns someshit which is decoded to `'Ñòðåëà'`

Code to decode `fix_encoding(audio['TIT2'].text[0])` , any help is appreciated )

**Comment by rspeer** [comment]
@jabbalaci, I think your text has unfortunately lost too much information.

I bet that at some point the text was `'WalldÃƒÂ©n'`. ftfy can fix that: it's been encoded as UTF-8 and decoded as Windows-1252, twice. However, on top of that, some software that wasn't expecting to see the rare character `ƒ` was replaced by a question mark.

I think there's nothing you can do but try to go to the source of the problem. What software is mixing up UTF-8 and Windows-1252? What software is replacing characters with question marks? (From experience, the answers may be "Excel for Windows" and "Excel for Mac", respectively.) Can you get the people responsible for the upstream data to use a consistent encoding, even though Excel sucks at UTF-8?

**Comment by rspeer** [comment]
@ArtemBernatskyy That one is a mixup between Windows-1251 and Windows-1252. You'd want `'Ñòðåëà'.encode('windows-1252').decode('windows-1251')`.

Both of these are single-byte encodings, which makes this the hardest case to try to auto-detect in ftfy -- see issue #18.

**Comment by ArtemBernatskyy** [comment]
@rspeer yeh, but i was looking for universal solution (

**Comment by jabbalaci** [comment]
Thanks for the answers. I tried a lot of things but I had to do it manually:

    fname = fname.replace("ÃÂ©", "é")
    fname = fname.replace("ÃÂ¶", "ö")
    fname = fname.replace("ÃÂ±", "ñ")
    fname = fname.replace("ÃÂ¤", "ä")
    fname = fname.replace("ÃÂ¼", "ü")
    fname = fname.replace("ÃÂµ", "ő")
    fname = fname.replace("ÃÂ¡", "á")
    fname = fname.replace("ÃÂÃÂ¼", "ü")
    fname = fname.replace("ÃÂÃÂ¶", "ö")
    fname = fname.replace("Ã¶", "ö")
    fname = fname.replace("ÃÂ", "Ö")
    fname = fname.replace("ÃÂÃÂ¤", "ä")
    fname = fname.replace("ÃÂ", "Å")
    fname = fname.replace("ÃÂ³", "ó")
    fname = fname.replace("Ã©", "é")
    fname = fname.replace("Ã±", "ñ")

Ugly, but works :) It is streamripper that produces these file names. streamripper should be patched.

**Comment by rspeer** [comment]
@jabbalaci Oh, so it's the Unicode replacement character �, not a literal question mark. (Both of them can show up in different encoding accidents.)

Unfortunately this is still really lossy, but maybe I can help you with your approach. I can mostly reconstruct the encoding mixup that produced this data -- it probably uses Latin-1 instead of the very similar Windows-1252, and then throws out the control characters. This would at least help you to generate the strings you need to replace:

```
def mangle_text(text):
    text = text.encode('utf-8').decode('latin-1').encode('utf-8').decode('latin-1')
    return re.sub('[\x80-\x9f]', '\ufffd', text)
```

For example:

```
>>> mangle_text('ñ')
'Ã�Â±'
```

But you'll probably see why I don't think even an improvement to ftfy would be able to fix this, which is that different common characters end up with the same representation:

```
>>> mangle_text('Å')
'Ã�Â�'

>>> mangle_text('Á')
'Ã�Â�'
```
