### ISSUE TITLE
fix faux umlauts

### ISSUE THREAD

**Issue by maddesigns** [LuminosoInsight/python-ftfy#87]
I have bad output from PDF that has faux umlauts, see 
`Schnell, laut, rücksichtslos. Raser spüren Frühlingsgefühle.`

It is no `ü (00FC   LATIN SMALL LETTER U WITH DIAERESIS)`

It is:
`0075   LATIN SMALL LETTER U`
`0308   COMBINING DIAERESIS`
tested via: https://ftfy.now.sh/?s=Fru%CC%88hlingsgefu%CC%88hle. 

Can ftfy fix that or isn't this in scope?

**Comment by rspeer** [comment]
Fixing this is NFC normalization, which is one of the fixes that ftfy (in Python) applies by default. So, yes.

simonw's web implementation only uses the `fix_encoding` part of ftfy, which is the exciting part, but ftfy includes other fixes too.

So you could get the ftfy Python library. Also, you don't _need_ ftfy just to be able to perform NFC normalization. Here's the way that's in the Python standard library, for example:

    >>> import unicodedata
    >>> unicodedata.normalize('NFC', 'rücksichtslos')
    'rücksichtslos'
