### ISSUE TITLE
"Nicol\u00c3\u00a1s" it's not being fixed

### ISSUE THREAD

**Issue by nilehmann** [LuminosoInsight/python-ftfy#88]
The string `"Nicol\u00c3\u00a1s"` it's not being fixed by `ftfy` I would expect the output of `ftfy.fix_text("Nicol\u00c3\u00a1s")` to be `"Nicolás"`.

I get a correct output when using the code at http://code.activestate.com/recipes/578243-repair-common-unicode-mistakes-after-theyve-been-m/. Could there it be a regression? or maybe I'm not using `ftfy` correctly?

**Comment by rspeer** [comment]
Oh good catch, this is a regression.

Although ftfy would prefer to leave short texts unfixed if it's uncertain, it shouldn't be uncertain about `NicolÃ¡s`, or about what could be the most frequently mojibaked word, `mÃ¡s`. The heuristic likes upside-down exclamation points (`\u00a1`) too much at the moment. I'll test a change to see if I can restore this case to being fixed.

**Comment by nilehmann** [comment]
This is amazing, thanks for the prompt reply 😃.
