### ISSUE TITLE
the ftfy cann't deal control chars in ascii table???

### ISSUE THREAD

**Issue by jekoie** [LuminosoInsight/python-ftfy#93]
i have a string   s=u"Raisecom(debug)## he\x08\x08help "  use 
ftfy.fix_text(unicode(s, errors='ignore'), remove_control_chars=False)   but it can't deal  \x08(back char) 
can anyone help me?

**Comment by rspeer** [comment]
I don't understand. You asked it to `ftfy` the text, but with `remove_control_chars=False`. The string comes out unchanged, because control characters are the only things that are odd about that string. You also used the `unicode()` constructor on a string that was already in Unicode.

Could you explain what your intended output is, and what output you get instead?

Use three backticks to paste code or output in a GitHub issue report:

    ```
    code goes here
    ```

**Comment by rspeer** [comment]
Feel free to report a new issue if you have output from ftfy that differs from what you wanted or expected, but this isn't an issue report.

**Comment by jekoie** [comment]
the s=u"Raisecom(debug)## he\x08\x08help " and i want to show s=u"Raisecom(debug)##help " this string after use ftfy, but ftfy can't work in my way.

**Comment by rspeer** [comment]
To produce a readable, understandable bug report, one thing you can do is to type the code that illustrates your problem at the Python prompt, and show the input and output.

The report shouldn't involve unrelated things that I have no information about such as `Raisecom` or `debug`, and output should be clearly different from input.

Despite all this, I think I've figured out what you're asking. Here's how you could say it:

> I am using ftfy 4.4.3 in Python 2.7. I have a string containing control characters that I would like ftfy to interpret as backspaces, but all I can get ftfy to do is to leave them alone or delete them:
>
> ```
> >>> import ftfy
> >>> s = u"he\x08\x08help"
> >>> ftfy.fix_text(s)
> u'hehelp'
>
> >>> ftfy.fix_text(s, remove_control_chars=False)
> >>> u'he\x08\x08help'
> ```
>
> The output I want is `u'help'`.

And then I would quickly give you an answer: ftfy doesn't do that. `\x08` is an instruction for an old terminal to backspace, and ftfy's job isn't to interpret these instructions -- it's not a terminal emulator.

**Comment by jekoie** [comment]
thanks,i will try.
