### ISSUE TITLE
Uncurl_quotes has an effect on other fixes.

### ISSUE THREAD

**Issue by mihow** [LuminosoInsight/python-ftfy#96]
Running `fix_text` with `uncurl_quotes=False` stops 2 non-quote characters from being fixed in the following sentence:

```python
text = """
Burkina Faso’s introduction activities are being implemented by the country’s Ministry of Health and key partner organizations, including UNFPA, Deutsche Gesellschaft fÃ¼r Internationale Zusammenarbeit (GIZ), Marie Stopes International (MSI), and the Association BurkinabÃ© pour le Bien-Etre Familial (ABBEF), with technical support from PATH.
"""
```

```python
ftfy.fix_text(text, uncurl_quotes=False)
>>> "Burkina Faso’s introduction activities are being implemented by the country’s Ministry of Health and key partner organizations, including UNFPA, Deutsche Gesellschaft fÃ¼r Internationale Zusammenarbeit (GIZ), Marie Stopes International (MSI), and the Association BurkinabÃ© pour le Bien-Etre Familial (ABBEF), with technical support from PATH."
```
```python
ftfy.fix_text(text, uncurl_quotes=True)
>>> "Burkina Faso's introduction activities are being implemented by the country's Ministry of Health and key partner organizations, including UNFPA, Deutsche Gesellschaft für Internationale Zusammenarbeit (GIZ), Marie Stopes International (MSI), and the Association Burkinabé pour le Bien-Etre Familial (ABBEF), with technical support from PATH."
```

**Comment by rspeer** [comment]
I'd say this is not a bug, it's a good example of why `uncurl_quotes` is part of ftfy, and why all the fixes are interspersed.

ftfy only allows the text encoding to _change_ at a hard line break. The encoding mixup that produces text such as "fÃ¼r" cannot also produce a curly apostrophe. The line is in an inconsistent encoding.

The most likely explanation for why the line ended up that way, of course, is that one process mojibaked the encoding, and then a second process auto-curled the apostrophe. Fixing this involves undoing the steps in reverse order: replacing the curly apostrophe with a straight ASCII one, then fixing the encoding mixup. If you don't allow the apostrophe to be un-curled, no fix is possible.

Thanks for the example, by the way, and I hope ftfy is helping you in general.

**Comment by mahnunchik** [comment]
Hi @rspeer @mihow 

How to fix it without change curly apostrophe to ASCII one?

For example I've string `it’s not a case Â you`.

**Comment by rspeer** [comment]
That's the `uncurl_quotes=False` option to `ftfy.fix_text` that the original issue reporter asked about.

**Comment by rspeer** [comment]
However, the text you posted is too ambiguous to be fixed with ftfy. I don't know what the text was supposed to be either, and "case Â you" looks like a plausible use of language even if it's not right.
