### ISSUE TITLE
Mojibake problem: Ã«

### ISSUE THREAD

**Issue by MicroJackson** [LuminosoInsight/python-ftfy#97]
Hi,
I have a problem with a piece of text that I need to fix.
The word that causes problems is: "ongeÃ«venaard". (It's Dutch)
When I put this in: `print(ftfy.fix_text("ongeÃ«venaard"))` I get the same mangled word back.
`print(ftfy.fixes.fix_one_step_and_explain("ongeÃ«venaard"))` This fixes my problem, and gives back the word that I want: "ongeëvenaard", with a plan how to fix it. However this does not seem like a usable way to fix a lot texts. (need to do this for millions of pieces of text, fix_text() works for ~99% of them)

After digging some in the ftfy.fixes and ftfy.badness, it seems that both words have no "weirdness" from the `def sequence_weirdness(text):` method. So the `def text_cost(text):` remains the same for both words, since it does have an "adjustment" of 1 in that method, so ftfy thinks the words are the same, when they obviously are not.

Anyhow, my question is if this is intentional behavior, and is it possible to fix? Is using the fix_one_step_and_explain() not a valid strategy? Help is appreciated.

PS: The letters:
`U+00C3  Ã       [Lu] LATIN CAPITAL LETTER A WITH TILDE`
`U+00AB  «       [Pi] LEFT-POINTING DOUBLE ANGLE QUOTATION MARK`

**Comment by rspeer** [comment]
Thanks for the report! It's not really intended. It's being overly conservative about double angle quotation marks.

In the case where there are only two characters of mojibake, and one of them is a reasonable punctuation mark, the boundary line can be very hard to draw. I have tried to draw such a boundary line anyway, with a pair of regular expressions in badness.py. But the expressions are just too careful around quotation marks.

I bet I can tweak the rules to fix a few more obvious cases such as `Ã«`.

**Comment by MicroJackson** [comment]
Awesome! Looking forward for an update then. I will keep it as is for now then.
If I can help in any way with the problem then give me a shout.
